const food = {
  Breakfast: {
    menuItems: [
      {
        category: 'Breakfast',
        id: 424113,
        title: 'Brioche Breakfast Sandwich',
        image:
          'https://images.spoonacular.com/file/wximages/424113-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'The Cheesefacke Factory',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Breakfast',
        id: 243991,
        title: 'Grilled Breakfast Sandwich',
        image:
          'https://images.spoonacular.com/file/wximages/243991-312x231.png',
        imageType: 'png',
        restaurantChain: 'Jack in the Box',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Breakfast',
        id: 330859,
        title: 'Grilled Breakfast Burrito - Bacon',
        image:
          'https://images.spoonacular.com/file/wximages/330859-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Taco Bell',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },

      {
        category: 'Breakfast',
        id: 389431,
        title: 'Breakfast Burrito, Bacon and Egg',
        image:
          'https://images.spoonacular.com/file/wximages/389431-312x231.png',
        imageType: 'png',
        restaurantChain: 'Amigos Kings Classic',
        servingSize: '182g',
        readableServingSize: '6 oz',
        servings: {
          number: 1,
          size: 182,
          unit: 'g',
        },
      },
      {
        category: 'Breakfast',
        id: 346917,
        title: 'Breakfast Sandwiches - Sausage Biscuit',
        image:
          'https://images.spoonacular.com/file/wximages/346917-312x231.png',
        imageType: 'png',
        restaurantChain: '7 Eleven',
        servingSize: '1 sandwich',
        readableServingSize: '1 sandwich',
        servings: {
          number: 1,
          size: 1,
          unit: 'sandwich',
        },
      },
      {
        category: 'Breakfast',
        id: 346916,
        title: 'Breakfast Sandwich - Croissant Breakfast Sandwich',
        image:
          'https://images.spoonacular.com/file/wximages/346916-312x231.png',
        imageType: 'png',
        restaurantChain: '7 Eleven',
        servingSize: '1 sandwich',
        readableServingSize: '1 sandwich',
        servings: {
          number: 1,
          size: 1,
          unit: 'sandwich',
        },
      },
      {
        category: 'Breakfast',
        id: 265101,
        title: 'Breakfast Sandwich w/ Homestyle Biscuit & Sausage',
        image:
          'https://images.spoonacular.com/file/wximages/265101-312x231.png',
        imageType: 'png',
        restaurantChain: 'Tim Hortons',
        servingSize: '113g',
        readableServingSize: '4 oz',
        servings: {
          number: 1,
          size: 113,
          unit: 'g',
        },
      },
      {
        category: 'Breakfast',
        id: 265103,
        title: 'Breakfast Sandwich w/ Homestyle Biscuit, Egg & Cheese',
        image:
          'https://images.spoonacular.com/file/wximages/265103-312x231.png',
        imageType: 'png',
        restaurantChain: 'Tim Hortons',
        servingSize: '145g',
        readableServingSize: '5 oz',
        servings: {
          number: 1,
          size: 145,
          unit: 'g',
        },
      },
      {
        category: 'Breakfast',
        id: 346918,
        title: 'Breakfast Sandwiches - English Muffin Breakfast Sandwich',
        image:
          'https://images.spoonacular.com/file/wximages/346918-312x231.png',
        imageType: 'png',
        restaurantChain: '7 Eleven',
        servingSize: '1 sandwich',
        readableServingSize: '1 sandwich',
        servings: {
          number: 1,
          size: 1,
          unit: 'sandwich',
        },
      },
      {
        category: 'Breakfast',
        id: 265104,
        title: 'Breakfast Sandwich w/ Homestyle Biscuit, Sausage & Cheese',
        image:
          'https://images.spoonacular.com/file/wximages/265104-312x231.png',
        imageType: 'png',
        restaurantChain: 'Tim Hortons',
        servingSize: '124g',
        readableServingSize: '4 oz',
        servings: {
          number: 1,
          size: 124,
          unit: 'g',
        },
      },
    ],
  },
  Appetizer: {
    menuItems: [
      {
        category: 'Appetizer',
        id: 298482,
        title: 'Pork & Bean Tostada Suiza',
        image:
          'https://images.spoonacular.com/file/wximages/298482-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Pepe's Mexican Restaurant",
        servingSize: '184g',
        readableServingSize: '1 Tostada',
        servings: {
          number: 1,
          size: 184,
          unit: 'g',
        },
      },
      {
        category: 'Appetizer',
        id: 377528,
        title: 'Oven-Roasted Wings - Double Order',
        image:
          'https://images.spoonacular.com/file/wximages/377528-312x231.png',
        imageType: 'png',
        restaurantChain: 'Boston Pizza',
        servingSize: '469g',
        readableServingSize: '17 oz',
        servings: {
          number: 1,
          size: 469,
          unit: 'g',
        },
      },
      {
        category: 'Appetizer',
        id: 377597,
        title: 'Fried Wings - Double Order',
        image:
          'https://images.spoonacular.com/file/wximages/377597-312x231.png',
        imageType: 'png',
        restaurantChain: 'Boston Pizza',
        servingSize: '483g',
        readableServingSize: '17 oz',
        servings: {
          number: 1,
          size: 483,
          unit: 'g',
        },
      },
      {
        category: 'Appetizer',
        id: 254190,
        title: 'Honey BBQ - Traditional Wings',
        image:
          'https://images.spoonacular.com/file/wximages/254190-312x231.png',
        imageType: 'png',
        restaurantChain: 'Pizza Hut',
        servingSize: '67g',
        readableServingSize: '2 oz',
        servings: {
          number: 1,
          size: 67,
          unit: 'g',
        },
      },
      {
        category: 'Appetizer',
        id: 254187,
        title: 'Garlic Parmesan - Traditional Wings',
        image:
          'https://images.spoonacular.com/file/wximages/254187-312x231.png',
        imageType: 'png',
        restaurantChain: 'Pizza Hut',
        servingSize: '56g',
        readableServingSize: '2 oz',
        servings: {
          number: 1,
          size: 56,
          unit: 'g',
        },
      },
      {
        category: 'Appetizer',
        id: 361615,
        title: 'Mini Corn Dogs',
        image:
          'https://images.spoonacular.com/file/wximages/361615-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Wienerschnitzel',
        servingSize: '6 pak',
        readableServingSize: 'Mini',
        servings: {
          number: 1,
          size: 6,
          unit: 'pak',
        },
      },
      {
        category: 'Appetizer',
        id: 298495,
        title: 'Beef & Bean Tostada Suiza',
        image:
          'https://images.spoonacular.com/file/wximages/298495-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Pepe's Mexican Restaurant",
        servingSize: '184g',
        readableServingSize: '1 Tostada',
        servings: {
          number: 1,
          size: 184,
          unit: 'g',
        },
      },
      {
        category: 'Appetizer',
        id: 254198,
        title: 'Spicy Asian, Crispy Bone In Wings',
        image:
          'https://images.spoonacular.com/file/wximages/254198-312x231.png',
        imageType: 'png',
        restaurantChain: 'Pizza Hut',
        servingSize: '82g',
        readableServingSize: '3 oz',
        servings: {
          number: 1,
          size: 82,
          unit: 'g',
        },
      },
      {
        category: 'Appetizer',
        id: 416975,
        title: 'Traditional Wings, Ghost Pepper Blazin',
        image:
          'https://images.spoonacular.com/file/wximages/416975-312x231.png',
        imageType: 'png',
        restaurantChain: 'Buffalo Wild Wings',
        servingSize: 'Single',
        readableServingSize: 'Single',
        servings: {
          number: 1,
          size: null,
          unit: 'Single',
        },
      },
      {
        category: 'Appetizer',
        id: 310161,
        title: 'Chicken & Bean Tostada',
        image:
          'https://images.spoonacular.com/file/wximages/310161-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Pepe's Mexican Restaurant",
        servingSize: '186g',
        readableServingSize: '1 Tostada',
        servings: {
          number: 1,
          size: 186,
          unit: 'g',
        },
      },
    ],
  },
  Salad: {
    menuItems: [
      {
        category: 'Salad',
        id: 387191,
        title: 'Fruit and Nut Salad',
        image:
          'https://images.spoonacular.com/file/wximages/387191-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Aladdin's Eatery",
        servingSize: '16oz',
        readableServingSize: '16 oz',
        servings: {
          number: 1,
          size: 16,
          unit: 'oz',
        },
      },
      {
        category: 'Salad',
        id: 387193,
        title: 'Grilled Turkey Salad',
        image:
          'https://images.spoonacular.com/file/wximages/387193-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Aladdin's Eatery",
        servingSize: '15oz',
        readableServingSize: '15 oz',
        servings: {
          number: 1,
          size: 15,
          unit: 'oz',
        },
      },
      {
        category: 'Salad',
        id: 273066,
        title: 'Salad Ole',
        image:
          'https://images.spoonacular.com/file/wximages/273066-312x231.png',
        imageType: 'png',
        restaurantChain: 'Taco Villa',
        servingSize: '11.2oz',
        readableServingSize: '11.2oz',
        servings: {
          number: 1,
          size: 11.2,
          unit: 'oz',
        },
      },
      {
        category: 'Salad',
        id: 351155,
        title: 'Salad Bar, Kidney Beans',
        image:
          'https://images.spoonacular.com/file/wximages/351155-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Godfather's Pizza",
        servingSize: '0.5 cup',
        readableServingSize: '0.5cup',
        servings: {
          number: 1,
          size: 0.5,
          unit: 'cup',
        },
      },
      {
        category: 'Salad',
        id: 331818,
        title: 'Salads, Famous House Salad (One Serving w/ Dressing)',
        image:
          'https://images.spoonacular.com/file/wximages/331818-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Olive Garden',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Salad',
        id: 331819,
        title: 'Salads, Famous House Salad (One Serving w/ Low-Fat Dressing)',
        image:
          'https://images.spoonacular.com/file/wximages/331819-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Olive Garden',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Salad',
        id: 384649,
        title: 'Fat Salad Wedge (no dressing)',
        image:
          'https://images.spoonacular.com/file/wximages/384649-312x231.png',
        imageType: 'png',
        restaurantChain: 'Fatburger',
        servingSize: '1 serving',
        readableServingSize: '1 serving',
        servings: {
          number: 1,
          size: 1,
          unit: 'serving',
        },
      },
      {
        category: 'Salad',
        id: 384650,
        title: 'Fat Salad Wedge w/ Chicken (no dressing)',
        image:
          'https://images.spoonacular.com/file/wximages/384650-312x231.png',
        imageType: 'png',
        restaurantChain: 'Fatburger',
        servingSize: '1 serving',
        readableServingSize: '1 serving',
        servings: {
          number: 1,
          size: 1,
          unit: 'serving',
        },
      },
      {
        category: 'Salad',
        id: 380960,
        title: 'Side Salad',
        image:
          'https://images.spoonacular.com/file/wximages/380960-312x231.png',
        imageType: 'png',
        restaurantChain: 'Roy Rogers Restaurants',
        servingSize: '1 serving',
        readableServingSize: '1 serving',
        servings: {
          number: 1,
          size: 1,
          unit: 'serving',
        },
      },
      {
        category: 'Salad',
        id: 243196,
        title: 'Chef Salad',
        image:
          'https://images.spoonacular.com/file/wximages/243196-312x231.png',
        imageType: 'png',
        restaurantChain: "Hungry Howie's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
    ],
  },
  Soup: {
    menuItems: [
      {
        category: 'Soup',
        id: 331823,
        title: 'Soups, Minestrone (One Serving)',
        image:
          'https://images.spoonacular.com/file/wximages/331823-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Olive Garden',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Soup',
        id: 291048,
        title: 'Wonton Soup',
        image:
          'https://images.spoonacular.com/file/wximages/291048-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Pei Wei Asian Diner',
        servingSize: null,
        readableServingSize: 'Cup',
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Soup',
        id: 291049,
        title: 'Wonton Soup',
        image:
          'https://images.spoonacular.com/file/wximages/291049-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Pei Wei Asian Diner',
        servingSize: null,
        readableServingSize: 'Bowl',
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Soup',
        id: 353344,
        title: 'Wedding Soup',
        image:
          'https://images.spoonacular.com/file/wximages/353344-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Eat n Park',
        servingSize: null,
        readableServingSize: '1 bowl',
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Soup',
        id: 254162,
        title: 'Egg Drop Soup, Gluten Free (Cup)',
        image:
          'https://images.spoonacular.com/file/wximages/254162-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "PF Chang's",
        servingSize: null,
        readableServingSize: 'Cup',
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Soup',
        id: 360758,
        title: 'GF Egg Drop Soup',
        image:
          'https://images.spoonacular.com/file/wximages/360758-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "PF Chang's",
        servingSize: '1 cup',
        readableServingSize: '1 cup',
        servings: {
          number: 1,
          size: 1,
          unit: 'cup',
        },
      },
      {
        category: 'Soup',
        id: 360756,
        title: 'GF Egg Drop Soup',
        image:
          'https://images.spoonacular.com/file/wximages/360756-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "PF Chang's",
        servingSize: '1 bowl',
        readableServingSize: '1 bowl',
        servings: {
          number: 1,
          size: 1,
          unit: 'bowl',
        },
      },
      {
        category: 'Soup',
        id: 353518,
        title: 'Thai Wonton Soup (cup)',
        image:
          'https://images.spoonacular.com/file/wximages/353518-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Pei Wei Asian Diner',
        servingSize: '1 cup',
        readableServingSize: 'Cup',
        servings: {
          number: 1,
          size: 1,
          unit: 'cup',
        },
      },
      {
        category: 'Soup',
        id: 318795,
        title: 'Clam Chowder (Large)',
        image:
          'https://images.spoonacular.com/file/wximages/318795-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Au Bon Pain',
        servingSize: '16 fl. oz',
        readableServingSize: 'Large',
        servings: {
          number: 1,
          size: 16,
          unit: 'fl oz',
        },
      },
      {
        category: 'Soup',
        id: 318797,
        title: 'Clam Chowder (Small)',
        image:
          'https://images.spoonacular.com/file/wximages/318797-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Au Bon Pain',
        servingSize: '8 fl. oz',
        readableServingSize: 'Small',
        servings: {
          number: 1,
          size: 8,
          unit: 'fl oz',
        },
      },
    ],
  },
  SideDish: {
    menuItems: [
      {
        category: 'SideDish',
        id: 423507,
        title: 'Premium Southwest Salad w/ Buttermilk Crispy Chicken',
        image:
          'https://images.spoonacular.com/file/wximages/423507-312x231.png',
        imageType: 'png',
        restaurantChain: "McDonald's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'SideDish',
        id: 423501,
        title: 'Premium Bacon Ranch Salad w/ Buttermilk Crispy Chicken',
        image:
          'https://images.spoonacular.com/file/wximages/423501-312x231.png',
        imageType: 'png',
        restaurantChain: "McDonald's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'SideDish',
        id: 323968,
        title:
          'No Rules Parmesan Pasta - w/ Grilled Chicken And Grilled Shrimp',
        image:
          'https://images.spoonacular.com/file/wximages/323968-312x231.png',
        imageType: 'png',
        restaurantChain: 'Outback',
        servingSize: '1 Total Meal',
        readableServingSize: '1 Total Meal',
        servings: {
          number: 1,
          size: 1,
          unit: 'Total Meal',
        },
      },
      {
        category: 'SideDish',
        id: 397257,
        title: 'Mini Chef Salad',
        image:
          'https://images.spoonacular.com/file/wximages/397257-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "My Friend's Place",
        servingSize: '10.76oz',
        readableServingSize: 'Mini',
        servings: {
          number: 1,
          size: 10.76,
          unit: 'oz',
        },
      },
      {
        category: 'SideDish',
        id: 424729,
        title: 'Fried Chicken Strips Cobb Salad (add dressing)',
        image:
          'https://images.spoonacular.com/file/wximages/424729-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Denny's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'SideDish',
        id: 424301,
        title:
          'Chicken Club Salad w/ Grilled Chicken Strips (w/o dressing or croutons)',
        image:
          'https://images.spoonacular.com/file/wximages/424301-312x231.png',
        imageType: 'png',
        restaurantChain: 'Jack in the Box',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'SideDish',
        id: 264580,
        title: 'Side Salad',
        image:
          'https://images.spoonacular.com/file/wximages/264580-312x231.png',
        imageType: 'png',
        restaurantChain: "Taco John's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'SideDish',
        id: 341811,
        title:
          'Mediterranean Salad w/ Roasted Chicken (add choice of baguette or muffin)',
        image:
          'https://images.spoonacular.com/file/wximages/341811-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Mimi's Cafe",
        servingSize: '19.5oz',
        readableServingSize: '19.5oz',
        servings: {
          number: 1,
          size: 19.5,
          unit: 'oz',
        },
      },
      {
        category: 'SideDish',
        id: 224617,
        title: 'Chopped Side Salad',
        image:
          'https://images.spoonacular.com/file/wximages/224617-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Arby's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'SideDish',
        id: 396254,
        title: 'Loaded Macaroni and Cheese',
        image:
          'https://images.spoonacular.com/file/wximages/396254-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Daily Grill',
        servingSize: '1 plating',
        readableServingSize: '1 plating',
        servings: {
          number: 1,
          size: 1,
          unit: 'plating',
        },
      },
    ],
  },
  MainCourse: {
    menuItems: [
      {
        category: 'MainCourse',
        id: 306263,
        title: 'Brown Rice Main Meal Salad',
        image: 'https://spoonacular.com/menuItemImages/salad.jpg',
        imageType: 'jpg',
        restaurantChain: "Mother's Market & Kitchen",
        servingSize: '1 serving',
        readableServingSize: '1 serving',
        servings: {
          number: 1,
          size: 1,
          unit: 'serving',
        },
      },
      {
        category: 'MainCourse',
        id: 365626,
        title: 'Mac and Cheese Main Squeeze!!! Sandwich',
        image: 'https://spoonacular.com/menuItemImages/sandwich.jpg',
        imageType: 'jpg',
        restaurantChain: '4food',
        servingSize: '1 sandwich',
        readableServingSize: '1 sandwich',
        servings: {
          number: 1,
          size: 1,
          unit: 'sandwich',
        },
      },
      {
        category: 'MainCourse',
        id: 348304,
        title: 'Grinder: Crispy Chicken Club',
        image:
          'https://images.spoonacular.com/file/wximages/348304-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'B C Pizza',
        servingSize: '1 each',
        readableServingSize: '1 each',
        servings: {
          number: 1,
          size: 1,
          unit: 'each',
        },
      },
      {
        category: 'MainCourse',
        id: 368825,
        title: 'Bacon 3-Cheese - Regular, 3-Size Menu Sandwiches',
        image: 'https://spoonacular.com/menuItemImages/sandwich.jpg',
        imageType: 'jpg',
        restaurantChain: "Charley's Grilled Subs",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'MainCourse',
        id: 387935,
        title: 'Albacore Solid White Tuna',
        image:
          'https://images.spoonacular.com/file/wximages/387935-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Gigi Cafe',
        servingSize: '340g',
        readableServingSize: '12 oz',
        servings: {
          number: 1,
          size: 340,
          unit: 'g',
        },
      },
      {
        category: 'MainCourse',
        id: 226635,
        title: 'Soup & Insalata',
        image:
          'https://images.spoonacular.com/file/wximages/226635-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Bertucci's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'MainCourse',
        id: 226633,
        title: 'Silano Calzone',
        image: 'https://spoonacular.com/menuItemImages/calzone.jpg',
        imageType: 'jpg',
        restaurantChain: "Bertucci's",
        servingSize: '1 Serving',
        readableServingSize: '1 Serving',
        servings: {
          number: 1,
          size: 1,
          unit: 'Serving',
        },
      },
      {
        category: 'MainCourse',
        id: 226630,
        title: 'Sauteed Chicken Piccata',
        image: 'https://spoonacular.com/menuItemImages/chicken-piccata.jpg',
        imageType: 'jpg',
        restaurantChain: "Bertucci's",
        servingSize: '1 Serving',
        readableServingSize: '1 Serving',
        servings: {
          number: 1,
          size: 1,
          unit: 'Serving',
        },
      },
      {
        category: 'MainCourse',
        id: 226628,
        title: 'Rigatoni, Broccoli & Chicken',
        image:
          'https://images.spoonacular.com/file/wximages/226628-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Bertucci's",
        servingSize: '1 Serving',
        readableServingSize: '1 Serving',
        servings: {
          number: 1,
          size: 1,
          unit: 'Serving',
        },
      },
      {
        category: 'MainCourse',
        id: 226624,
        title: 'Meatball Calzone',
        image: 'https://spoonacular.com/menuItemImages/calzone.jpg',
        imageType: 'jpg',
        restaurantChain: "Bertucci's",
        servingSize: '1 Serving',
        readableServingSize: '1 Serving',
        servings: {
          number: 1,
          size: 1,
          unit: 'Serving',
        },
      },
    ],
  },
  Bread: {
    menuItems: [
      {
        category: 'Bread',
        id: 342861,
        title: 'Bread Sandwich, Pokket',
        image: 'https://spoonacular.com/menuItemImages/sandwich.jpg',
        imageType: 'jpg',
        restaurantChain: "D'Angelo Grilled Sandwiches",
        servingSize: null,
        readableServingSize: 'Medium',
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Bread',
        id: 417660,
        title: 'Grilled Cheese on Classic White Bread',
        image: 'https://spoonacular.com/menuItemImages/grilled-cheese.jpg',
        imageType: 'jpg',
        restaurantChain: 'Panera Bread',
        servingSize: 'Kids',
        readableServingSize: 'Kids',
        servings: {
          number: 1,
          size: null,
          unit: 'Kids',
        },
      },
      {
        category: 'Bread',
        id: 271228,
        title: 'Red Snapper, Breaded & Grilled',
        image:
          'https://images.spoonacular.com/file/wximages/271228-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'K&W Cafeterias',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Bread',
        id: 227035,
        title: 'Strawberry Bread',
        image:
          'https://images.spoonacular.com/file/wximages/227035-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Bob Evans',
        servingSize: '62g',
        readableServingSize: '2 oz',
        servings: {
          number: 1,
          size: 62,
          unit: 'g',
        },
      },
      {
        category: 'Bread',
        id: 266875,
        title: 'Tuna on Wheat Bread',
        image:
          'https://images.spoonacular.com/file/wximages/266875-312x231.png',
        imageType: 'png',
        restaurantChain: 'Wawa',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Bread',
        id: 315026,
        title: 'Sunrise Subway Melt on 6" Flatbread - Egg White',
        image: 'https://spoonacular.com/menuItemImages/turkey-sub.png',
        imageType: 'png',
        restaurantChain: 'Subway',
        servingSize: '1 Sandwich',
        readableServingSize: '1 Sandwich',
        servings: {
          number: 1,
          size: 1,
          unit: 'Sandwich',
        },
      },
      {
        category: 'Bread',
        id: 417527,
        title: 'Lipton Brisk Raspberry Tea',
        image: 'https://spoonacular.com/menuItemImages/cup-of-tea.jpg',
        imageType: 'jpg',
        restaurantChain: 'Panera Bread',
        servingSize: 'Medium (20 fl. oz)',
        readableServingSize: 'Medium20floz',
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Bread',
        id: 249461,
        title: 'Pork Adobo Flatbread',
        image:
          'https://images.spoonacular.com/file/wximages/249461-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Noodles & Company',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Bread',
        id: 224792,
        title: 'Whole Wheat Multigrain Bread',
        image:
          'https://images.spoonacular.com/file/wximages/224792-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Au Bon Pain',
        servingSize: '4oz',
        readableServingSize: '4 oz',
        servings: {
          number: 1,
          size: 4,
          unit: 'oz',
        },
      },
      {
        category: 'Bread',
        id: 248010,
        title: "Gambino's Muffuletta Bread",
        image: 'https://spoonacular.com/menuItemImages/sandwich.jpg',
        imageType: 'jpg',
        restaurantChain: "McAlister's Deli",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
    ],
  },
  Dessert: {
    menuItems: [
      {
        category: 'Dessert',
        id: 363733,
        title: 'Apple Turnover (w/o Cinnamon Sugar Topping)',
        image:
          'https://images.spoonacular.com/file/wximages/363733-312x231.png',
        imageType: 'png',
        restaurantChain: "Hardee's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Dessert',
        id: 224549,
        title: 'Cherry Turnover',
        image:
          'https://images.spoonacular.com/file/wximages/224549-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Arby's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Dessert',
        id: 375517,
        title: 'Turnover',
        image:
          'https://images.spoonacular.com/file/wximages/375517-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Chester's",
        servingSize: '1 Each',
        readableServingSize: '1 Each',
        servings: {
          number: 1,
          size: 1,
          unit: 'Each',
        },
      },
      {
        category: 'Dessert',
        id: 224548,
        title: 'Apple Turnover',
        image:
          'https://images.spoonacular.com/file/wximages/224548-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Arby's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Dessert',
        id: 354301,
        title: 'Euro Tart',
        image:
          'https://images.spoonacular.com/file/wximages/354301-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: '16 Handles',
        servingSize: '1 fl. oz',
        readableServingSize: '1 fl oz',
        servings: {
          number: 1,
          size: 1,
          unit: 'fl oz',
        },
      },
      {
        category: 'Dessert',
        id: 331908,
        title: 'Dolcini (Mini Desserts), Strawberry & White Chocolate Cake',
        image:
          'https://images.spoonacular.com/file/wximages/331908-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Olive Garden',
        servingSize: null,
        readableServingSize: 'Mini',
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Dessert',
        id: 424871,
        title: 'Shareable Turtle Sundae',
        image:
          'https://images.spoonacular.com/file/wximages/424871-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Denny's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Dessert',
        id: 354343,
        title: 'Watermelon Tart',
        image:
          'https://images.spoonacular.com/file/wximages/354343-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: '16 Handles',
        servingSize: '1 fl. oz',
        readableServingSize: '1 fl oz',
        servings: {
          number: 1,
          size: 1,
          unit: 'fl oz',
        },
      },
      {
        category: 'Dessert',
        id: 354336,
        title: 'Red Velvet Cake',
        image:
          'https://images.spoonacular.com/file/wximages/354336-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: '16 Handles',
        servingSize: '1 fl. oz',
        readableServingSize: '1 fl oz',
        servings: {
          number: 1,
          size: 1,
          unit: 'fl oz',
        },
      },
      {
        category: 'Dessert',
        id: 424701,
        title: 'Yogurt',
        image:
          'https://images.spoonacular.com/file/wximages/424701-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Denny's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
    ],
  },
  Sauce: {
    menuItems: [
      {
        category: 'Sauce',
        id: 375525,
        title: 'Honey Mustard Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/375525-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Chester's",
        servingSize: '1 Sauce',
        readableServingSize: '1 Sauce',
        servings: {
          number: 1,
          size: 1,
          unit: 'Sauce',
        },
      },
      {
        category: 'Sauce',
        id: 333604,
        title: 'Blue Cheese Dipping Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/333604-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Dominos',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Sauce',
        id: 233624,
        title: 'Honey Mustard Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/233624-312x231.png',
        imageType: 'png',
        restaurantChain: "Church's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Sauce',
        id: 254168,
        title: 'Crispy Green Beans Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/254168-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "PF Chang's",
        servingSize: '57g',
        readableServingSize: '2 oz',
        servings: {
          number: 1,
          size: 57,
          unit: 'g',
        },
      },
      {
        category: 'Sauce',
        id: 380590,
        title: 'Garlic Butter Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/380590-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Cottage Inn Pizza',
        servingSize: '1oz',
        readableServingSize: '1 oz',
        servings: {
          number: 1,
          size: 1,
          unit: 'oz',
        },
      },
      {
        category: 'Sauce',
        id: 254315,
        title: 'Wing Blue Cheese Dipping Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/254315-312x231.png',
        imageType: 'png',
        restaurantChain: 'Pizza Hut',
        servingSize: '43g',
        readableServingSize: '2 oz',
        servings: {
          number: 1,
          size: 43,
          unit: 'g',
        },
      },
      {
        category: 'Sauce',
        id: 422268,
        title: 'HOT-N-Ready Crazy Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/422268-312x231.png',
        imageType: 'png',
        restaurantChain: 'Little Caesars Pizza',
        servingSize: '1 sauce cup',
        readableServingSize: '1 saucecup',
        servings: {
          number: 1,
          size: 1,
          unit: 'sauce',
        },
      },
      {
        category: 'Sauce',
        id: 362242,
        title: 'Spaghetti and Meat Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/362242-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Zio's Italian Kitchen",
        servingSize: '1 plating',
        readableServingSize: '1 plating',
        servings: {
          number: 1,
          size: 1,
          unit: 'plating',
        },
      },
      {
        category: 'Sauce',
        id: 375524,
        title: 'BBQ Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/375524-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Chester's",
        servingSize: '1 Sauce',
        readableServingSize: '1 Sauce',
        servings: {
          number: 1,
          size: 1,
          unit: 'Sauce',
        },
      },
      {
        category: 'Sauce',
        id: 425084,
        title: 'Honey BBQ Sauce',
        image:
          'https://images.spoonacular.com/file/wximages/425084-312x231.png',
        imageType: 'png',
        restaurantChain: "Church's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
    ],
  },
  Fingerfood: {
    menuItems: [
      {
        category: 'Fingerfood',
        id: 420782,
        title: "Mini Corn Dogs 'n Fries",
        image:
          'https://images.spoonacular.com/file/wximages/420782-312x231.png',
        imageType: 'png',
        restaurantChain: "Steak N' Shake",
        servingSize: 'Kids',
        readableServingSize: 'Mini',
        servings: {
          number: 1,
          size: null,
          unit: 'Kids',
        },
      },
      {
        category: 'Fingerfood',
        id: 400005,
        title: 'Ground Beef Quesadilla',
        image:
          'https://images.spoonacular.com/file/wximages/400005-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Jimboys Tacos',
        servingSize: '1 standard portio',
        readableServingSize: '1 standard portio',
        servings: {
          number: 1,
          size: 1,
          unit: 'standard portio',
        },
      },
      {
        category: 'Fingerfood',
        id: 395733,
        title: "Kid's Mini Corn Dog Kid's Meal w/ Small Fry (no drink)",
        image:
          'https://images.spoonacular.com/file/wximages/395733-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Runza',
        servingSize: null,
        readableServingSize: "Kid's",
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Fingerfood',
        id: 312930,
        title: 'Nachos Grande',
        image:
          'https://images.spoonacular.com/file/wximages/312930-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'FINS Mexican Eatery',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Fingerfood',
        id: 330872,
        title: 'Beefy Nacho Loaded Griller',
        image:
          'https://images.spoonacular.com/file/wximages/330872-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Taco Bell',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Fingerfood',
        id: 389452,
        title: '3-Meat Breakfast Quesadilla',
        image:
          'https://images.spoonacular.com/file/wximages/389452-312x231.png',
        imageType: 'png',
        restaurantChain: 'Amigos Kings Classic',
        servingSize: '253g',
        readableServingSize: '9 oz',
        servings: {
          number: 1,
          size: 253,
          unit: 'g',
        },
      },
      {
        category: 'Fingerfood',
        id: 426068,
        title: 'Grill and Bar Quesadilla - Smoked Chicken (w/o side fries)',
        image:
          'https://images.spoonacular.com/file/wximages/426068-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Chili's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Fingerfood',
        id: 318359,
        title: 'Grill and Bar Bacon Ranch Beef Quesadilla',
        image:
          'https://images.spoonacular.com/file/wximages/318359-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Chili's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Fingerfood',
        id: 318332,
        title: 'Grill and Bar Classic Nachos - Beef',
        image:
          'https://images.spoonacular.com/file/wximages/318332-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: "Chili's",
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Fingerfood',
        id: 395804,
        title: '5 Piece Mini Corn Dogs',
        image:
          'https://images.spoonacular.com/file/wximages/395804-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Runza',
        servingSize: null,
        readableServingSize: '5 Piece',
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
    ],
  },
  Beverage: {
    menuItems: [
      {
        category: 'Beverage',
        id: 368288,
        title: 'Fountain Beverage',
        image:
          'https://spoonacular.com/menuItemImages/plastic-to-go-drink-cup.jpg',
        imageType: 'jpg',
        restaurantChain: "Famous Dave's",
        servingSize: '8 fl. oz',
        readableServingSize: '8 fl oz',
        servings: {
          number: 1,
          size: 8,
          unit: 'fl oz',
        },
      },
      {
        category: 'Beverage',
        id: 345885,
        title: "Child's Beverage",
        image:
          'https://spoonacular.com/menuItemImages/plastic-to-go-drink-cup.jpg',
        imageType: 'jpg',
        restaurantChain: 'Western Sizzlin',
        servingSize: '12oz',
        readableServingSize: '12 fl oz',
        servings: {
          number: 1,
          size: 12,
          unit: 'oz',
        },
      },
      {
        category: 'Beverage',
        id: 302617,
        title: 'Optimal Sports Beverage',
        image:
          'https://spoonacular.com/menuItemImages/plastic-to-go-drink-cup.jpg',
        imageType: 'jpg',
        restaurantChain: 'Parrot-Ice',
        servingSize: null,
        readableServingSize: null,
        servings: {
          number: 1,
          size: null,
          unit: null,
        },
      },
      {
        category: 'Beverage',
        id: 370310,
        title: 'Dairyland 1% M.F. Chocolate Milk Beverage',
        image:
          'https://spoonacular.com/menuItemImages/plastic-to-go-drink-cup.jpg',
        imageType: 'jpg',
        restaurantChain: 'De Dutch Pannekoek House',
        servingSize: '250grams',
        readableServingSize: '250 grams',
        servings: {
          number: 1,
          size: 250,
          unit: 'grams',
        },
      },
      {
        category: 'Beverage',
        id: 422956,
        title: 'Dairy Queen Arctic Rush Frozen Beverage, All Flavors',
        image:
          'https://images.spoonacular.com/file/wximages/422956-312x231.png',
        imageType: 'png',
        restaurantChain: 'DQ',
        servingSize: 'Large',
        readableServingSize: 'Large',
        servings: {
          number: 1,
          size: null,
          unit: 'Large',
        },
      },
      {
        category: 'Beverage',
        id: 269465,
        title: "O' douls, malt beverage Non-alcoholic bee",
        image:
          'https://spoonacular.com/menuItemImages/plastic-to-go-drink-cup.jpg',
        imageType: 'jpg',
        restaurantChain: "Ruby's Diner",
        servingSize: '361g',
        readableServingSize: '12 fl oz',
        servings: {
          number: 1,
          size: 361,
          unit: 'g',
        },
      },
      {
        category: 'Beverage',
        id: 422954,
        title: 'Dairy Queen Arctic Rush Frozen Beverage, All Flavors',
        image:
          'https://images.spoonacular.com/file/wximages/422954-312x231.png',
        imageType: 'png',
        restaurantChain: 'DQ',
        servingSize: 'Small',
        readableServingSize: 'Small',
        servings: {
          number: 1,
          size: null,
          unit: 'Small',
        },
      },
      {
        category: 'Beverage',
        id: 316578,
        title: 'Cool Lime Starbucks Refreshers Beverage',
        image:
          'https://images.spoonacular.com/file/wximages/316578-312x231.jpg',
        imageType: 'jpg',
        restaurantChain: 'Starbucks',
        servingSize: '16 fl. oz',
        readableServingSize: '16 fl oz',
        servings: {
          number: 1,
          size: 16,
          unit: 'fl oz',
        },
      },
      {
        category: 'Beverage',
        id: 263268,
        title: 'Valencia Orange Starbucks Refreshers Beverage',
        image:
          'https://images.spoonacular.com/file/wximages/263268-312x231.png',
        imageType: 'png',
        restaurantChain: 'Starbucks',
        servingSize: '16 fl. oz',
        readableServingSize: '16 fl oz',
        servings: {
          number: 1,
          size: 16,
          unit: 'fl oz',
        },
      },
      {
        category: 'Beverage',
        id: 422955,
        title: 'Dairy Queen Arctic Rush Frozen Beverage, All Flavors',
        image:
          'https://images.spoonacular.com/file/wximages/422955-312x231.png',
        imageType: 'png',
        restaurantChain: 'DQ',
        servingSize: 'Medium',
        readableServingSize: 'Medium',
        servings: {
          number: 1,
          size: null,
          unit: 'Medium',
        },
      },
    ],
  },
};

export default food;
